#%RAML 1.0 Trait
usage: Use this trait for resources that could respond with a 204 status
responses:
    204:
      description: The request executed successfully without any content to show as response
