#%RAML 1.0
title: Test API
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/bb18f05b-0d1c-4197-a3ff-3eba405eb901/api/{version} # baseUri: https://my-server/api/{version}
mediaType:
  - application/json
version: v1
protocols: [ HTTPS ]

securitySchemes: 
  basicAuth: !include securitySchemes/basicAuth.raml
securedBy: [ basicAuth ]
types:
  Customer: !include types/Customer.raml
  Error: !include types/Error.raml
traits:
  hasResponseCollection: !include traits/hasResponseCollection.raml
  hasNotFound: !include traits/hasNotFound.raml
  hasNoContent: !include traits/hasNoContent.raml
  pageable: !include traits/pageable.raml
  cacheable: !include traits/content-cacheable.raml
  
/customers:
  get:
    description: Get list of customers
    is: 
      - hasResponseCollection
      - pageable
      - cacheable
    queryParameters:
      firstName?: string
  post:
    description: Create a new customer
    body:
      application/json:
        type: Customer
        example: !include examples/Customer.json
    responses:
      201:
        description: Successfully created a new customer
  /{id}:
    uriParameters: 
      id: 
        description: the customer id sent in path
    put:
      description: Update an existing customer by id
      body:
        application/json:
          type: Customer
          example: !include examples/Customer.json
      is: 
        - hasNotFound
        - hasNoContent
    delete:
      description: Delete an existing customer by id
      is: 
        - hasNotFound
        - hasNoContent
